---
- name: Example showing VMware module creating vm
  hosts: denvansible01
  gather_facts: no
  vars:
#    ansible_python_interpreter: "/usr/bin/env python"
#    ansible_connection: local
     ansible_python_interpreter: "/home/ansible/venv/bin/python"
  tasks:

     - debug: var=input

     - name: Create a virtual machine on given ESXi hostname
       community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        folder: "{{ input.folder }}"
        datacenter: TEST
        name: "{{ input.name }}"
        state: absent
        guest_id: "{{ input.guest_id }}"
        cluster: "{{ cluster }}"
        disk:
        - size_gb: "{{ input.disk.size_gb }}"
          type: thin
          datastore: VM_INFRA_TEST
        hardware:
          memory_mb: "{{ input.hardware.memory_mb }}"
          num_cpus: 2
          scsi: paravirtual
       register: deploy_vm

     - debug: var=input

     - debug: var=statdata

     - debug: var=deploy_vm

# ansible-playbook basic_crea_maquina_module.yml -i ./hosts.yml

