---
- name: Example showing VMware module creating vm
  hosts: denvansible01
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
     - name: Create a virtual machine on given ESXi hostname
       community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        folder: /TEST/vm
        datacenter: TEST
        name: test_vm_0002
        state: poweredoff 
        guest_id: centos64Guest
        cluster: "{{ cluster }}"
        disk:
        - size_gb: 10
          type: thin
          datastore: VM_INFRA_TEST
        hardware:
          memory_mb: 512
          num_cpus: 2
          scsi: paravirtual
       register: deploy_vm


# ansible-playbook basic_crea_maquina_module.yml -i ./hosts.yml

