
all:
 hosts:
  localhost:
 vars:
    ansible_connection: local
    vcenter_user: ansible@vsphere.test
    vcenter_pass: 4Ns!BLE01
    vcenter_server: denvtestsvc01.leprino.local
    vcenter_username: ansible@vsphere.test
    vcenter_password: 4Ns!BLE01
    vcenter_hostname: denvtestsvc01.leprino.local
    esxi_hostname: denvtestsvc011111
    cluster: SYSTEMS

    dir_sh: /home/ansible/REPOS/LEPR
    dir_sh: /home/ansible/mi_entorno_virtual/REPOS/LEPR



    ping_cmd: " ping -c 20 -i 0.5 "
    ping_cmd: " ping -c 1 "
    obm_enviroment_list:
      - "pre"
      - "interna"
      - "externa"
