all:
 hosts:
  localhost:
  VMWARE_BASTION:
  denvansible01:

 vars:
    ssh_port: 22
    ansible_user: ansible
    vcenter_user: ansible@vsphere.test
    vcenter_pass: 4Ns!BLE01
    vcenter_server: denvtestsvc01.leprino.local
    vcenter_username: ansible@vsphere.test
    vcenter_password: 4Ns!BLE01
    vcenter_hostname: denvtestsvc01.leprino.local
    esxi_hostname: denvtestsvc011111
    cluster: SYSTEMS
    preprocess_dir: /home/ansible/mi_entorno_virtual/REPOS/LEPR
    preprocess_dir: /home/ansible/REPOS/LEPR
    preprocess_cmd: hostname
    in:
        folder: /TEST/vm
        name: test_workflow_machine
        guest_id: centos64Guest
        disk:
          size_gb: 10
        hardware:
          memory_mb: 512