---
- name: Preprocess input data
  hosts: denvansible01
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - name: Change the working directory to somedir/ before executing the command
      shell: "{{ preprocess_cmd }}"
      args:
         chdir: "{{ preprocess_dir }}"
      register: out

    - debug: var=out
    - debug: var=input

    - name: "Artifact URL of test results to Tower Workflows"
      set_stats:
        data:
          statdata:  "Prueba intra workflows"
# ansible-playbook preprocess.yml -i ./hosts.yml