---
- name: Preprocess input data
  hosts: denvansible01
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - name: 'Fail when a mandatory extra vars are not defined'
      fail:
         msg: '{{ ansible_play_name }}: - required variables not defined'
      when:
          in.folder is not defined or in.name is not defined or in.disk.size_gb is not defined or in.hardware.memory_mb is not defined

    - name: Change the working directory to somedir/ before executing the command
      shell: "{{ preprocess_cmd }}"
      args:
         chdir: "{{ preprocess_dir }}"
      register: out

    - debug: var=out
    - debug: var=input

    - name: "Artifact URL of test results to Tower Workflows"
      set_stats:
        data:
          input:  "{{ in }} "

   - name: "Artifact URL of test results to Tower Workflows"
      set_stats:
        data:
          statdata:  "{{ in }} "

    - debug: var=input

# ansible-playbook preprocess.yml -i ./hosts.yml