---
- name: Preprocess input data
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - name: Change the working directory to somedir/ before executing the command
      shell: "./preprocess.sh"
      args:
         chdir: "{{ dir_sh }}"
      register: out

    - debug: var=out

# ansible-playbook preprocess.yml -i ./hosts.yml
